name: Build and Push Services

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Get the tag
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build and tag latest docker image
        run: |
          docker build .

      - name: Tag versioned image
        run: docker tag ghcr.io/${{ github.repository_owner }}/network_graph_api:latest ghcr.io/${{ github.repository_owner }}/network_graph_api:${{ steps.vars.outputs.tag }}

      - name: Push the images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/network_graph_api:latest
          docker push ghcr.io/${{ github.repository_owner }}/network_graph_api:${{ steps.vars.outputs.tag}}
